# POST http://localhost:3000/api/signup

# {
#     "email": "alsgks1@test.com",
#     "password": "1234567aA(",
#     "passwordCheck":"1234567aA("
# }


# GET https://cpro95.tistory.com/71

//GET https://youtu.be/9rttwV8sgZs?si=afDk37X3C4ODb9KZ

// GET https://cafe.naver.com/livehope/464444

GET https://m.cafe.naver.com/ca-fe/web/cafes/uvacenter/articles/649853