import "./globals.css";
import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";

const nanumGothic = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={nanumGothic.className}>
        <>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster />
        </>
      </body>
    </html>
  );
}
